import {
    LayoutDashboard,
    Briefcase,
    Users,
    FileText,
    MessageSquare,
    Settings,
    User,
    Calendar,
    Shield,
    CreditCard,
    LogOut,
    Star,
    Clock,
    FolderOpen,
    BarChart3,
    ClipboardCheck,
    Eye,
    Edit3,
    UserCheck
} from 'lucide-react';

export const NAV_ITEMS = {
    worker: [
        { label: 'Dashboard', href: '/worker', icon: LayoutDashboard },
        { label: 'Profile', href: '/worker/profile', icon: User },
        { label: 'View My Profile', href: '/worker/view-profile', icon: Eye },
        { label: 'My Schedule', href: '/worker/schedule', icon: Calendar },
        { label: 'Find Jobs', href: '/worker/jobs', icon: Briefcase },
        { label: 'My Clients', href: '/worker/clients', icon: Users },
        { label: 'Invoices', href: '/worker/invoices', icon: FileText },
        { label: 'Timesheets', href: '/worker/timesheets', icon: Clock },
        { label: 'Reviews', href: '/worker/reviews', icon: Star },
        { label: 'Documents', href: '/worker/documents', icon: FolderOpen },
        { label: 'Reports', href: '/worker/reports', icon: ClipboardCheck },
        { label: 'Analytics', href: '/worker/analytics', icon: BarChart3 },
        { label: 'Messages', href: '/worker/inbox', icon: MessageSquare, badge: 4 },
        { label: 'Settings', href: '/worker/settings', icon: Settings },
    ],
    client: [
        { label: 'Dashboard', href: '/client', icon: LayoutDashboard },
        { label: 'My Profile', href: '/client/profile', icon: User },
        { label: 'Sessions', href: '/client/sessions', icon: Calendar },
        { label: 'Support Workers', href: '/client/workers', icon: Users },
        { label: 'Job Listings', href: '/client/jobs', icon: Briefcase },
        { label: 'Documents', href: '/client/documents', icon: FolderOpen },
        { label: 'Reviews', href: '/client/reviews', icon: Star },
        { label: 'Messages', href: '/client/inbox', icon: MessageSquare, badge: 2 },
        { label: 'Settings', href: '/client/settings', icon: Settings },
    ],
    admin: [
        { label: 'Overview', href: '/admin', icon: LayoutDashboard },
        { label: 'Users', href: '/admin/users', icon: Users },
        { label: 'Agreements', href: '/admin/agreements', icon: Shield },
        { label: 'Invoices', href: '/admin/invoices', icon: FileText },
        { label: 'Messages', href: '/admin/messages', icon: MessageSquare },
        { label: 'Settings', href: '/admin/settings', icon: Settings },
        {label :' Services', href:'/admin/services', icon:Briefcase},   
    ],
};
