import {
  LayoutDashboard,
  Briefcase,
  Users,
  FileText,
  MessageSquare,
  Settings,
  User,
  Calendar,
  Shield,
  CreditCard,
  LogOut,
  Star,
  Clock,
  FolderOpen,
  BarChart3,
  ClipboardCheck,
  Eye,
  Edit3,
  UserCheck,
  Pencil,
  Info,
} from "lucide-react";

export const NAV_ITEMS = {
  worker: [
    { label: "Dashboard", href: "/worker", icon: LayoutDashboard },
    { label: "Edit Profile", href: "/worker/profile", icon: Pencil },
    { label: "View My Profile", href: "/worker/view-profile", icon: Eye },
    { label: "Find Jobs", href: "/worker/jobs", icon: Briefcase },
    { label: "Agreements", href: "/worker/agreement", icon: ClipboardCheck },

    { label: "Sessions", href: "/worker/sessions", icon: Calendar },
    // { label: "My Clients", href: "/worker/clients", icon: Users },
    { label: "Invoice", href: "/worker/invoice", icon: FileText },
    // { label: "Timesheets", href: "/worker/timesheets", icon: Clock },
    { label: "Documents", href: "/worker/documents", icon: FolderOpen },
    { label: "Messages", href: "/worker/inbox", icon: MessageSquare },
    { label: "Payments", href: "/worker/payments", icon: CreditCard },
    { label: "Settings", href: "/worker/settings", icon: Settings },
  ],
  client: [
    { label: "Dashboard", href: "/client", icon: LayoutDashboard },
    { label: "Profile", href: "/client/profile", icon: User },
    { label: "Job Listings", href: "/client/jobs", icon: Briefcase },
    { label: "Find Support Workers", href: "/client/workers", icon: Users },
    { label: "CALD support", href: "/client/cald-support", icon: Info },
    { label: "Agreements", href: "/client/agreements", icon: ClipboardCheck },
    { label: "Sessions", href: "/client/sessions", icon: Calendar },
    { label: "Invoice", href: "/client/invoice", icon: FileText },
    { label: "Messages", href: "/client/inbox", icon: MessageSquare },
    // { label: "Reviews", href: "/client/reviews", icon: Star },
    { label: "Settings", href: "/client/settings", icon: Settings },
  ],
  admin: [
    { label: "Overview", href: "/admin", icon: LayoutDashboard },
    { label: "Users", href: "/admin/users", icon: Users },
    { label: "Agreements", href: "/admin/agreements", icon: Shield },
    { label: "Invoices", href: "/admin/invoices", icon: FileText },
    { label: "Payments", href: "/admin/payments", icon: CreditCard },
    {
      label: "Messages",
      href: "/admin/messages",
      icon: MessageSquare,
    },
    { label: "Settings", href: "/admin/settings", icon: Settings },
    // {label :' Services', href:'/admin/services', icon:Briefcase},
  ],
};
